### signup user maya
POST http://localhost:6688/api/signup
Content-Type: application/json

{
    "workspace": "rust",
    "fullname": "maya",
    "email": "maya@qq.com",
    "password": "2713"
}

### signup user alice
POST http://localhost:6688/api/signup
Content-Type: application/json

{
    "workspace": "rust",
    "fullname": "alice",
    "email": "alice@qq.com",
    "password": "2713"
}

### signin user(valid)
# @name signin
POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "maya@qq.com",
    "password": "2713"
}



### signin user(invalid)
POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "maya1@qq.com",
    "password": "2713"
}


### create chat
POST http://localhost:6688/api/chats
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "acme",
    "members": [1, 2],
    "public": false
}

### get chat list
@token = {{signin.response.body.token}}
GET http://localhost:6688/api/chats
Authorization: Bearer {{token}}
Content-Type: application/json

### get user list
GET http://localhost:6688/api/users
Authorization: Bearer {{token}}
Content-Type: application/json
